---
- name: NodeJS - Install dependencies if missing
  become: true
  apt:
    name:
      - git
      - curl
      - build-essential
      - libssl-dev
    state: present

- include: nvm.yml

- include: node.yml

- include: verify.yml

- include: npm-packages.yml
