---
- name: Docker - install apt package dependencies
  become: true
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common

- name: Docker - Add Dockers official GPG Key
  become: true
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Docker - Install Docker
  become: true
  apt:
    name: docker.io
    state: latest
    update_cache: "yes"

- name: Docker - Create docker group
  group:
    name: docker
    state: present

- name: Docker - Add current user to docker group
  become: true
  user:
    name: "{{ ansible_user }}"
    groups: ["docker"]
    append: "yes"

- name: Docker - Start docker on boot
  become: true
  service:
    name: "docker"
    enabled: "yes"

- name: Docker - Check current docker-compose version.
  command: docker-compose --version
  register: docker_compose_current_version
  changed_when: false
  failed_when: false

- name: Docker - Delete existing docker-compose version if it is different
  become: true
  file:
    path: "{{ docker_compose_path }}"
    state: absent
  when: >
    docker_compose_current_version.stdout is defined
    and docker_compose_version not in docker_compose_current_version.stdout

- name: Docker - Install docker compose
  become: true
  get_url:
    url: https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-x86_64
    dest: "{{ docker_compose_path }}"
    mode: 0755
