---
- name: Snaps - Install snapd apt dependency
  become: true
  apt:
    name: snapd
    state: present

- name: Snaps - Install common snaps
  become: true
  snap:
    name: "{{ item.name }}"
    channel: "{{ item.channel | default('stable') }}"
    classic: "{{ item.classic | default('no') }}"
  with_items: "{{ snaps_common }}"
